try{
    throw "error is this"
}
catch(error){
console.log(error)}